In [23]:
import numpy as np

from numpy import matrix, sin, cos

from ase.io import read

In [24]:
# optional, leave as 0. otherwise

molecule = read('N_linear.xyz')

cellW = W.get_cell()
print(cellW)


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [25]:
from ase.build import fcc111
slab = fcc111('Ni', size=[2, 4, 3], a=3.55, orthogonal=True)
cell = slab.get_cell()

In [26]:


W.rotate('z', np.pi / 2, center=(0, 0, 0))

from ase.visualize import view
view(W)
